### ISSUE TITLE
Remove spacing between cards

### ISSUE THREAD

**Issue by ghostsquad** [vaemendis/hccd#1]
I was just poking at this, and looking at the example. It seems that HCCD adds a small amount of space between cards. This means that I have to make multiple cuts per card when I print them out. Can this be changed/configurable?

**Comment by ghostsquad** [comment]
As I look more at this, it appears to be because Chrome has some default styles for tables. So the fix is probably just to explicitly set the styles... I'll create a PR for this

**Comment by vaemendis** [comment]
You could achieve the same result (in Firefox) just by adding these lines to your CSS file:

```
table {   
    border-collapse: collapse;   
}


table td {
    padding: 0;
}
```

For Chrome, you would need to also add a small negative margin to your card CSS:

```
.card {
    margin: -0.2mm;
    ...
```

**Comment by ghostsquad** [comment]
@vaemendis the PR seems to fix the issue in both Chrome and Firefox without requiring a change to card css.

![image](https://user-images.githubusercontent.com/903488/30935303-1b541596-a385-11e7-9f58-04c55fa9095b.png)

**Comment by ghostsquad** [comment]
I'm looking forward to the next release with this change! :)
