### ISSUE TITLE
Possible typo of "th"?

### ISSUE THREAD

**Issue by ghostsquad** [vaemendis/hccd#3]
Is this a typo?
https://github.com/vaemendis/hccd/blob/master/src/main/java/net/vaemendis/hccd/CardGenerator.java#L62

I think this should be `th` for table header?

**Comment by ghostsquad** [comment]
Upon further investigation, it seems like this should actually be `tr`...

**Comment by vaemendis** [comment]
Indeed.
I fixed it.
