### ISSUE TITLE
No variable listing

### ISSUE THREAD

**Issue by CliqueChaser** [vaemendis/hccd#6]
I'm having to figure out what some variables do and the differences between variables with similar names.  I love the program overall, it's great, but if you could create a variable reference document describing the variables and their functions, that'd be great.

Some examples:

- Traditionally "float" means a decimal-type variable so I was confused before I figured out it stood for the alignment in Hccd.
- Had to do some experimentation to figure out the difference between "font" and "font-family".  

Creating a variable reference would be hugely helpful and would help avoid these frustrating issues.

**Comment by vaemendis** [comment]
HCCD uses standard CSS syntax.
You can find an exhaustive list of CSS properties here:
https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Keyword_index
